myuser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import include, path
from . import views


from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('register/', views.registerPage, name="register"),
    #path('profil/', views.userPage, name="user-page"),
    path('profile/', views.profile, name='user-profile'),
    path('', views.ustalist, name="usta"),
	path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),    
    path('ajax/load-ilce/', views.load_ilce, name='ajax_load_ilce'),
    path('addusta/', views.createUsta, name="create_usta")

    
   ] + static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Il(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Ilce(models.Model):
    il = models.ForeignKey(Il, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Usta(models.Model):
    user =  models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    website = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    telefon = models.CharField(max_length=200, null=True)
    desc = models.TextField(max_length=1000, null=True)
    il = models.ForeignKey(Il, on_delete=models.SET_NULL, null=True)
    ilce = models.ForeignKey(Ilce, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(default='ananas.jpg',
                              upload_to='profile_images')

    def __str__(self):
        return self.name 

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.forms import ModelForm
from .models import Usta




from .models import Usta, Ilce




class UstaForm(ModelForm):
    class Meta:
         model = Usta
         fields = ('name', 'category', 'il','ilce', 'website', 'email', 'desc', 'telefon', 'image')


         
    


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']



 

user/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Usta, Ilce
from .forms import UstaForm, CreateUserForm
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .decorators import unauthenticated_user


@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Basariyla kayit oldunuz ' +
                             user + '. Devam etmek icin lutfen giris yapin.')

            return redirect('login')
    context = {'form': form}
    return render(request, 'register.html', context)


@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('usta')
        else:
            messages.info(
                request, 'kullanici adi VEYA parolayi yanlis girdiniz')
    context = {}
    return render(request, 'login.html', context)



@login_required(login_url='login')
def profile(request):
    return render(request, 'user.html')




def logoutUser(request):
    logout(request)
    return redirect('login')


def createUsta(request):
    form = UstaForm()
    if request.method == 'POST':
        #print('Printing POST:', request.POST)
        form = UstaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form':form}
    return render(request, 'form.html', context)

def ustalist(request):
    usta = Usta.objects.all()
    return render(request, 'home.html', {'usta': usta})
    

def home(request):
    context = {}
    return render(request, 'home.html', context)


def load_ilce(request):
    il_id = request.GET.get('il')
    ilce = Ilce.objects.filter(il_id=il_id).order_by('name')
    return render(request, 'user/ilce_dropdown_list_options.html', {'ilce': ilce})

templates/base.html
{% load static %}
<!doctype html>
<meta charset="utf-8">
    <title>{% block title %}Usta Database{% endblock %}</title>

    
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  <head>
    
  </head>
  <body>
    <h1>Usta Veritabani</h1>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>

user/templates/form.html
<form action="" id="ustaForm" method="POST" data-ilce-url="{% url 'ajax_load_ilce' %}" novalidate>

    {% csrf_token %}

    
    {{form}}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_il").change(function () {
      var url = $("#ustaForm").attr("data-ilce-url");  
      var ilId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'il': ilId       
        },
        success: function (data) {  
          $("#id_ilce").html(data);  
        }
      });

    });
  </script>
<input type="submit" name="Submit">

</form>

user/templates/home.html
{% extends 'base.html' %}

{% block title %}Ananas{% endblock %}

{% block content %}

<a class="btn btn-primary  btn-sm btn-block" href="{% url 'create_usta' %}">Create Usta</a>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
      $("#ddlCategory,#ddlIl").on("change", function () {
          var category = $('#ddlCategory').find("option:selected").val();
          var il = $('#ddlIl').find("option:selected").val();
          SearchData(category, il)
      });
  });
  function SearchData(category, il) {
      if (category.toUpperCase() == 'ALL' && il.toUpperCase() == 'ALL') {
          $('#table11 tbody tr').show();
      } else {
          $('#table11 tbody tr:has(td)').each(function () {
              var rowCategory = $.trim($(this).find('td:eq(1)').text());
              var rowIl = $.trim($(this).find('td:eq(2)').text());
              if (category.toUpperCase() != 'ALL' && il.toUpperCase() != 'ALL') {
                  if (rowCategory.toUpperCase() == category.toUpperCase() && rowIl == il) {
                      $(this).show();
                  } else {
                      $(this).hide();
                  }
              } else if ($(this).find('td:eq(1)').text() != '' || $(this).find('td:eq(1)').text() != '') {
                  if (category != 'all') {
                      if (rowCategory.toUpperCase() == category.toUpperCase()) {
                          $(this).show();
                      } else {
                          $(this).hide();
                      }
                  }
                  if (il != 'all') {
                      if (rowIl == il) {
                          $(this).show();
                      }
                      else {
                          $(this).hide();
                      }
                  }
              }

          });
      }
  }
</script>
  <h2>Tum Ustalar</h2>

  <p>
    <a href="{% url 'create_usta' %}">Kayit Ol</a>
  </p>

  <style>
    .hello-msg{
      font-size: 18px;
      margin-right:20px;
    }
  </style>



  <style>
    #table11 {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    #table11 td, #customers th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #table11 tr:nth-child(even){background-color: #f2f2f2;}
    
    #table11 tr:hover {background-color: #ddd;}
    
    #table11 th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #3059c9;
      color: white;
    }
    </style>

<select class="cl_category" id="ddlCategory">
  <option value="all">Kategori Sec </option>
  <option value="Boya Badana">Boya Badana</option>
  <option value="Elektrik">Elektrik</option>
  <option value="Cam Balkon">Cam Balkon</option>
</select>
<select class="cl_il" id="ddlIl">
  <option value="all">Il Sec </option>
  <option value="Istanbul">Istanbul</option>
  <option value="Ankara">Ankara</option>
  <option value="Izmir">Izmir</option>
</select>

{% if not request.user.is_authenticated %}
<span><a class="hello-msg" href="{% url 'login' %}">Giris Yap</a></span>
<span><a class="hello-msg" href="{% url 'register' %}">Kayit Ol</a></span>
{% else %}
<span class="hello-msg"> Merhaba, {{request.user}}</span>
<span><a class="hello-msg" href="{% url 'logout' %}">Cikis Yap</a></span>
{% endif %}

  <table id="table11" border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Kategori</th>
        <th>Il</th>
        <th>Ilce</th>
        <th>Website</th>
        <th>Telefon</th>
        <th>E-Posta</th>
      </tr>
    </thead>
    <tbody>
      {% for usta in usta %}
        <tr>
          <td><a href="{% url 'create_usta' %}">{{ usta.name }}</a></td>
          <td>{{ usta.category.name }}</td>
          <td>{{ usta.il.name }}</td>
          <td>{{ usta.ilce.name }}</td>
          <td>{{ usta.website }}</td>
          <td>{{ usta.telefon }}</td>
          <td>{{ usta.email }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4"> <a href="{% url 'create_usta' %}">Ilk kayit olan siz olun</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>


{% endblock %}

user/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

user/templates/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">ANANAS'A KAYIT OL</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.first_name}}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.last_name}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>
						



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Kayit Ol">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Ananas'a coktan uye misiniz? <a href="{% url 'login' %}" class="ml-2">Giris Yap</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Kullanici Adi...';
		form_fields[2].placeholder='E-Posta...';
		form_fields[3].placeholder='Isim...';
		form_fields[4].placeholder='Soyisim...';
		form_fields[5].placeholder='Sifre Giriniz...';
		form_fields[6].placeholder='Tekrar Sifre Giriniz...';
		


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

user/templates/user.html
{% block content %}
<div class="row my-4">
    <div class="col-md-4"></div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header bg-info text-white">
                Usta Profil Sayfasi
            </div>
            <div class="row p-3">
                <div class="col-md-8">
                    <table class="table table-borderless">
                        <thead>
                            <span class="h4">{{ user.username }} profili</span class="h4">
                         
                            <hr>
                        </thead>
                        <tbody>
                            <div class="col-md-4">
                                <img class="img-thumbnail" src="{{ user.usta.image.url }}" alt="profile-image">
                            </div>
                            <tr>
                                <th scope="row">Kullanici Ismi</th>
                                <td>{{ user.username }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Firma veya Usta Adi</th>
                                <td>{{ user.usta.name }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Kategori</th>
                                <td>{{ user.usta.category }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Website</th>
                                <td>{{ user.usta.website }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Email</th>
                                <td>{{ user.email }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Phone</th>
                                <td>{{ user.usta.telefon }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Aciklama</th>
                                <td>{{ user.usta.desc }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Il</th>
                                <td>{{ user.usta.il }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Ilce</th>
                                <td>{{ user.usta.ilce }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

user/templates/user/ilce_dropdown_list_options.html
<option value="">---------</option>
{% for ilce in ilce %}
<option value="{{ ilce.pk }}">{{ ilce.name }}</option>
{% endfor %}

user/templates/user/user.html
<h1>Usta Profile</h1>

{% extends 'base.html' %}

{% block content %}

  <h2>Usta Form</h2>

  <form method="post" id="ustaForm" data-ilce-url="{% url 'ajax_load_ilce' %}" novalidate>
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
    <button type="submit">Kayit Ol</button>
    <a href="{% url 'usta_changelist' %}">Geri Don</a>
  </form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_il").change(function () {
      var url = $("#ustaForm").attr("data-ilce-url");  
      var ilId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'il': ilId       
        },
        success: function (data) {  
          $("#id_ilce").html(data);  
        }
      });

    });
  </script>


{% endblock %}

user/templates/user/usta_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Usta Form</h2>

  <form method="post" id="ustaForm" data-ilce-url="{% url 'ajax_load_ilce' %}" novalidate>
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
    <button type="submit">Kayit Ol</button>
    <a href="{% url 'usta_changelist' %}">Geri Don</a>
  </form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_il").change(function () {
      var url = $("#ustaForm").attr("data-ilce-url");  
      var ilId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'il': ilId       
        },
        success: function (data) {  
          $("#id_ilce").html(data);  
        }
      });

    });
  </script>


{% endblock %}

user/templates/user/usta_list.html
{% extends 'base.html' %}

{% block title %}Ananas{% endblock %}

{% block content %}

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
      $("#ddlCategory,#ddlIl").on("change", function () {
          var category = $('#ddlCategory').find("option:selected").val();
          var il = $('#ddlIl').find("option:selected").val();
          SearchData(category, il)
      });
  });
  function SearchData(category, il) {
      if (category.toUpperCase() == 'ALL' && il.toUpperCase() == 'ALL') {
          $('#table11 tbody tr').show();
      } else {
          $('#table11 tbody tr:has(td)').each(function () {
              var rowCategory = $.trim($(this).find('td:eq(1)').text());
              var rowIl = $.trim($(this).find('td:eq(2)').text());
              if (category.toUpperCase() != 'ALL' && il.toUpperCase() != 'ALL') {
                  if (rowCategory.toUpperCase() == category.toUpperCase() && rowIl == il) {
                      $(this).show();
                  } else {
                      $(this).hide();
                  }
              } else if ($(this).find('td:eq(1)').text() != '' || $(this).find('td:eq(1)').text() != '') {
                  if (category != 'all') {
                      if (rowCategory.toUpperCase() == category.toUpperCase()) {
                          $(this).show();
                      } else {
                          $(this).hide();
                      }
                  }
                  if (il != 'all') {
                      if (rowIl == il) {
                          $(this).show();
                      }
                      else {
                          $(this).hide();
                      }
                  }
              }

          });
      }
  }
</script>
  <h2>Tum Ustalar</h2>

  <p>
    <a href="{% url 'usta_add' %}">Kayit Ol</a>
  </p>

  <style>
    .hello-msg{
      font-size: 18px;
      margin-right:20px;
    }
  </style>

  <span class="hello-msg"> Merhaba, {{request.user}}</span>
  <span><a class="hello-msg" href="{% url 'logout' %}">Cikis Yap</a></span>

  <style>
    #table11 {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    #table11 td, #customers th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #table11 tr:nth-child(even){background-color: #f2f2f2;}
    
    #table11 tr:hover {background-color: #ddd;}
    
    #table11 th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #3059c9;
      color: white;
    }
    </style>

<select class="cl_category" id="ddlCategory">
  <option value="all">Kategori Sec </option>
  <option value="Boya Badana">Boya Badana</option>
  <option value="Elektrik">Elektrik</option>
  <option value="Cam Balkon">Cam Balkon</option>
</select>
<select class="cl_il" id="ddlIl">
  <option value="all">Il Sec </option>
  <option value="Istanbul">Istanbul</option>
  <option value="Ankara">Ankara</option>
  <option value="Izmir">Izmir</option>
</select>


  <table id="table11" border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Kategori</th>
        <th>Il</th>
        <th>Ilce</th>
        <th>Website</th>
        <th>Telefon</th>
        <th>E-Posta</th>
      </tr>
    </thead>
    <tbody>
      {% for usta in usta %}
        <tr>
          <td><a href="{% url 'usta_change' usta.pk %}">{{ usta.name }}</a></td>
          <td>{{ usta.category.name }}</td>
          <td>{{ usta.il.name }}</td>
          <td>{{ usta.ilce.name }}</td>
          <td>{{ usta.website }}</td>
          <td>{{ usta.telefon }}</td>
          <td>{{ usta.email }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'usta_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}